/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppHiddenLayoutRouteImport } from './routes/app/_hiddenLayout'
import { Route as AppHiddenLayoutAuthedRouteImport } from './routes/app/_hiddenLayout/_authed'
import { Route as AppHiddenLayoutQuickViewProductRouteImport } from './routes/app/_hiddenLayout/quick-view/product'
import { Route as AppHiddenLayoutAuthedViewProductRouteImport } from './routes/app/_hiddenLayout/_authed/view-product'
import { Route as AppHiddenLayoutAuthedStoragesRouteImport } from './routes/app/_hiddenLayout/_authed/storages'
import { Route as AppHiddenLayoutAuthedInventoryRouteImport } from './routes/app/_hiddenLayout/_authed/inventory'
import { Route as AppHiddenLayoutAuthedAppSettingsRouteImport } from './routes/app/_hiddenLayout/_authed/app-settings'
import { Route as AppHiddenLayoutAuthedAddProductRouteImport } from './routes/app/_hiddenLayout/_authed/add-product'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHiddenLayoutRoute = AppHiddenLayoutRouteImport.update({
  id: '/app/_hiddenLayout',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHiddenLayoutAuthedRoute = AppHiddenLayoutAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppHiddenLayoutRoute,
} as any)
const AppHiddenLayoutQuickViewProductRoute =
  AppHiddenLayoutQuickViewProductRouteImport.update({
    id: '/quick-view/product',
    path: '/quick-view/product',
    getParentRoute: () => AppHiddenLayoutRoute,
  } as any)
const AppHiddenLayoutAuthedViewProductRoute =
  AppHiddenLayoutAuthedViewProductRouteImport.update({
    id: '/view-product',
    path: '/view-product',
    getParentRoute: () => AppHiddenLayoutAuthedRoute,
  } as any)
const AppHiddenLayoutAuthedStoragesRoute =
  AppHiddenLayoutAuthedStoragesRouteImport.update({
    id: '/storages',
    path: '/storages',
    getParentRoute: () => AppHiddenLayoutAuthedRoute,
  } as any)
const AppHiddenLayoutAuthedInventoryRoute =
  AppHiddenLayoutAuthedInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AppHiddenLayoutAuthedRoute,
  } as any)
const AppHiddenLayoutAuthedAppSettingsRoute =
  AppHiddenLayoutAuthedAppSettingsRouteImport.update({
    id: '/app-settings',
    path: '/app-settings',
    getParentRoute: () => AppHiddenLayoutAuthedRoute,
  } as any)
const AppHiddenLayoutAuthedAddProductRoute =
  AppHiddenLayoutAuthedAddProductRouteImport.update({
    id: '/add-product',
    path: '/add-product',
    getParentRoute: () => AppHiddenLayoutAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppHiddenLayoutAuthedRouteWithChildren
  '/app/add-product': typeof AppHiddenLayoutAuthedAddProductRoute
  '/app/app-settings': typeof AppHiddenLayoutAuthedAppSettingsRoute
  '/app/inventory': typeof AppHiddenLayoutAuthedInventoryRoute
  '/app/storages': typeof AppHiddenLayoutAuthedStoragesRoute
  '/app/view-product': typeof AppHiddenLayoutAuthedViewProductRoute
  '/app/quick-view/product': typeof AppHiddenLayoutQuickViewProductRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppHiddenLayoutAuthedRouteWithChildren
  '/app/add-product': typeof AppHiddenLayoutAuthedAddProductRoute
  '/app/app-settings': typeof AppHiddenLayoutAuthedAppSettingsRoute
  '/app/inventory': typeof AppHiddenLayoutAuthedInventoryRoute
  '/app/storages': typeof AppHiddenLayoutAuthedStoragesRoute
  '/app/view-product': typeof AppHiddenLayoutAuthedViewProductRoute
  '/app/quick-view/product': typeof AppHiddenLayoutQuickViewProductRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/_hiddenLayout': typeof AppHiddenLayoutRouteWithChildren
  '/app/_hiddenLayout/_authed': typeof AppHiddenLayoutAuthedRouteWithChildren
  '/app/_hiddenLayout/_authed/add-product': typeof AppHiddenLayoutAuthedAddProductRoute
  '/app/_hiddenLayout/_authed/app-settings': typeof AppHiddenLayoutAuthedAppSettingsRoute
  '/app/_hiddenLayout/_authed/inventory': typeof AppHiddenLayoutAuthedInventoryRoute
  '/app/_hiddenLayout/_authed/storages': typeof AppHiddenLayoutAuthedStoragesRoute
  '/app/_hiddenLayout/_authed/view-product': typeof AppHiddenLayoutAuthedViewProductRoute
  '/app/_hiddenLayout/quick-view/product': typeof AppHiddenLayoutQuickViewProductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app'
    | '/app/add-product'
    | '/app/app-settings'
    | '/app/inventory'
    | '/app/storages'
    | '/app/view-product'
    | '/app/quick-view/product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/app/add-product'
    | '/app/app-settings'
    | '/app/inventory'
    | '/app/storages'
    | '/app/view-product'
    | '/app/quick-view/product'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/app/_hiddenLayout'
    | '/app/_hiddenLayout/_authed'
    | '/app/_hiddenLayout/_authed/add-product'
    | '/app/_hiddenLayout/_authed/app-settings'
    | '/app/_hiddenLayout/_authed/inventory'
    | '/app/_hiddenLayout/_authed/storages'
    | '/app/_hiddenLayout/_authed/view-product'
    | '/app/_hiddenLayout/quick-view/product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AppHiddenLayoutRoute: typeof AppHiddenLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_hiddenLayout': {
      id: '/app/_hiddenLayout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppHiddenLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_hiddenLayout/_authed': {
      id: '/app/_hiddenLayout/_authed'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppHiddenLayoutAuthedRouteImport
      parentRoute: typeof AppHiddenLayoutRoute
    }
    '/app/_hiddenLayout/quick-view/product': {
      id: '/app/_hiddenLayout/quick-view/product'
      path: '/quick-view/product'
      fullPath: '/app/quick-view/product'
      preLoaderRoute: typeof AppHiddenLayoutQuickViewProductRouteImport
      parentRoute: typeof AppHiddenLayoutRoute
    }
    '/app/_hiddenLayout/_authed/view-product': {
      id: '/app/_hiddenLayout/_authed/view-product'
      path: '/view-product'
      fullPath: '/app/view-product'
      preLoaderRoute: typeof AppHiddenLayoutAuthedViewProductRouteImport
      parentRoute: typeof AppHiddenLayoutAuthedRoute
    }
    '/app/_hiddenLayout/_authed/storages': {
      id: '/app/_hiddenLayout/_authed/storages'
      path: '/storages'
      fullPath: '/app/storages'
      preLoaderRoute: typeof AppHiddenLayoutAuthedStoragesRouteImport
      parentRoute: typeof AppHiddenLayoutAuthedRoute
    }
    '/app/_hiddenLayout/_authed/inventory': {
      id: '/app/_hiddenLayout/_authed/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppHiddenLayoutAuthedInventoryRouteImport
      parentRoute: typeof AppHiddenLayoutAuthedRoute
    }
    '/app/_hiddenLayout/_authed/app-settings': {
      id: '/app/_hiddenLayout/_authed/app-settings'
      path: '/app-settings'
      fullPath: '/app/app-settings'
      preLoaderRoute: typeof AppHiddenLayoutAuthedAppSettingsRouteImport
      parentRoute: typeof AppHiddenLayoutAuthedRoute
    }
    '/app/_hiddenLayout/_authed/add-product': {
      id: '/app/_hiddenLayout/_authed/add-product'
      path: '/add-product'
      fullPath: '/app/add-product'
      preLoaderRoute: typeof AppHiddenLayoutAuthedAddProductRouteImport
      parentRoute: typeof AppHiddenLayoutAuthedRoute
    }
  }
}

interface AppHiddenLayoutAuthedRouteChildren {
  AppHiddenLayoutAuthedAddProductRoute: typeof AppHiddenLayoutAuthedAddProductRoute
  AppHiddenLayoutAuthedAppSettingsRoute: typeof AppHiddenLayoutAuthedAppSettingsRoute
  AppHiddenLayoutAuthedInventoryRoute: typeof AppHiddenLayoutAuthedInventoryRoute
  AppHiddenLayoutAuthedStoragesRoute: typeof AppHiddenLayoutAuthedStoragesRoute
  AppHiddenLayoutAuthedViewProductRoute: typeof AppHiddenLayoutAuthedViewProductRoute
}

const AppHiddenLayoutAuthedRouteChildren: AppHiddenLayoutAuthedRouteChildren = {
  AppHiddenLayoutAuthedAddProductRoute: AppHiddenLayoutAuthedAddProductRoute,
  AppHiddenLayoutAuthedAppSettingsRoute: AppHiddenLayoutAuthedAppSettingsRoute,
  AppHiddenLayoutAuthedInventoryRoute: AppHiddenLayoutAuthedInventoryRoute,
  AppHiddenLayoutAuthedStoragesRoute: AppHiddenLayoutAuthedStoragesRoute,
  AppHiddenLayoutAuthedViewProductRoute: AppHiddenLayoutAuthedViewProductRoute,
}

const AppHiddenLayoutAuthedRouteWithChildren =
  AppHiddenLayoutAuthedRoute._addFileChildren(
    AppHiddenLayoutAuthedRouteChildren,
  )

interface AppHiddenLayoutRouteChildren {
  AppHiddenLayoutAuthedRoute: typeof AppHiddenLayoutAuthedRouteWithChildren
  AppHiddenLayoutQuickViewProductRoute: typeof AppHiddenLayoutQuickViewProductRoute
}

const AppHiddenLayoutRouteChildren: AppHiddenLayoutRouteChildren = {
  AppHiddenLayoutAuthedRoute: AppHiddenLayoutAuthedRouteWithChildren,
  AppHiddenLayoutQuickViewProductRoute: AppHiddenLayoutQuickViewProductRoute,
}

const AppHiddenLayoutRouteWithChildren = AppHiddenLayoutRoute._addFileChildren(
  AppHiddenLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AppHiddenLayoutRoute: AppHiddenLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
