/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppHiddenLayoutRouteImport } from './routes/app/_hiddenLayout'
import { Route as AppHiddenLayoutViewProductRouteImport } from './routes/app/_hiddenLayout/view-product'
import { Route as AppHiddenLayoutStoragesRouteImport } from './routes/app/_hiddenLayout/storages'
import { Route as AppHiddenLayoutInventoryRouteImport } from './routes/app/_hiddenLayout/inventory'
import { Route as AppHiddenLayoutAppSettingsRouteImport } from './routes/app/_hiddenLayout/app-settings'
import { Route as AppHiddenLayoutAddProductRouteImport } from './routes/app/_hiddenLayout/add-product'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHiddenLayoutRoute = AppHiddenLayoutRouteImport.update({
  id: '/app/_hiddenLayout',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHiddenLayoutViewProductRoute =
  AppHiddenLayoutViewProductRouteImport.update({
    id: '/view-product',
    path: '/view-product',
    getParentRoute: () => AppHiddenLayoutRoute,
  } as any)
const AppHiddenLayoutStoragesRoute = AppHiddenLayoutStoragesRouteImport.update({
  id: '/storages',
  path: '/storages',
  getParentRoute: () => AppHiddenLayoutRoute,
} as any)
const AppHiddenLayoutInventoryRoute =
  AppHiddenLayoutInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AppHiddenLayoutRoute,
  } as any)
const AppHiddenLayoutAppSettingsRoute =
  AppHiddenLayoutAppSettingsRouteImport.update({
    id: '/app-settings',
    path: '/app-settings',
    getParentRoute: () => AppHiddenLayoutRoute,
  } as any)
const AppHiddenLayoutAddProductRoute =
  AppHiddenLayoutAddProductRouteImport.update({
    id: '/add-product',
    path: '/add-product',
    getParentRoute: () => AppHiddenLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppHiddenLayoutRouteWithChildren
  '/app/add-product': typeof AppHiddenLayoutAddProductRoute
  '/app/app-settings': typeof AppHiddenLayoutAppSettingsRoute
  '/app/inventory': typeof AppHiddenLayoutInventoryRoute
  '/app/storages': typeof AppHiddenLayoutStoragesRoute
  '/app/view-product': typeof AppHiddenLayoutViewProductRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppHiddenLayoutRouteWithChildren
  '/app/add-product': typeof AppHiddenLayoutAddProductRoute
  '/app/app-settings': typeof AppHiddenLayoutAppSettingsRoute
  '/app/inventory': typeof AppHiddenLayoutInventoryRoute
  '/app/storages': typeof AppHiddenLayoutStoragesRoute
  '/app/view-product': typeof AppHiddenLayoutViewProductRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/_hiddenLayout': typeof AppHiddenLayoutRouteWithChildren
  '/app/_hiddenLayout/add-product': typeof AppHiddenLayoutAddProductRoute
  '/app/_hiddenLayout/app-settings': typeof AppHiddenLayoutAppSettingsRoute
  '/app/_hiddenLayout/inventory': typeof AppHiddenLayoutInventoryRoute
  '/app/_hiddenLayout/storages': typeof AppHiddenLayoutStoragesRoute
  '/app/_hiddenLayout/view-product': typeof AppHiddenLayoutViewProductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app'
    | '/app/add-product'
    | '/app/app-settings'
    | '/app/inventory'
    | '/app/storages'
    | '/app/view-product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/app/add-product'
    | '/app/app-settings'
    | '/app/inventory'
    | '/app/storages'
    | '/app/view-product'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/app/_hiddenLayout'
    | '/app/_hiddenLayout/add-product'
    | '/app/_hiddenLayout/app-settings'
    | '/app/_hiddenLayout/inventory'
    | '/app/_hiddenLayout/storages'
    | '/app/_hiddenLayout/view-product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AppHiddenLayoutRoute: typeof AppHiddenLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_hiddenLayout': {
      id: '/app/_hiddenLayout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppHiddenLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_hiddenLayout/view-product': {
      id: '/app/_hiddenLayout/view-product'
      path: '/view-product'
      fullPath: '/app/view-product'
      preLoaderRoute: typeof AppHiddenLayoutViewProductRouteImport
      parentRoute: typeof AppHiddenLayoutRoute
    }
    '/app/_hiddenLayout/storages': {
      id: '/app/_hiddenLayout/storages'
      path: '/storages'
      fullPath: '/app/storages'
      preLoaderRoute: typeof AppHiddenLayoutStoragesRouteImport
      parentRoute: typeof AppHiddenLayoutRoute
    }
    '/app/_hiddenLayout/inventory': {
      id: '/app/_hiddenLayout/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppHiddenLayoutInventoryRouteImport
      parentRoute: typeof AppHiddenLayoutRoute
    }
    '/app/_hiddenLayout/app-settings': {
      id: '/app/_hiddenLayout/app-settings'
      path: '/app-settings'
      fullPath: '/app/app-settings'
      preLoaderRoute: typeof AppHiddenLayoutAppSettingsRouteImport
      parentRoute: typeof AppHiddenLayoutRoute
    }
    '/app/_hiddenLayout/add-product': {
      id: '/app/_hiddenLayout/add-product'
      path: '/add-product'
      fullPath: '/app/add-product'
      preLoaderRoute: typeof AppHiddenLayoutAddProductRouteImport
      parentRoute: typeof AppHiddenLayoutRoute
    }
  }
}

interface AppHiddenLayoutRouteChildren {
  AppHiddenLayoutAddProductRoute: typeof AppHiddenLayoutAddProductRoute
  AppHiddenLayoutAppSettingsRoute: typeof AppHiddenLayoutAppSettingsRoute
  AppHiddenLayoutInventoryRoute: typeof AppHiddenLayoutInventoryRoute
  AppHiddenLayoutStoragesRoute: typeof AppHiddenLayoutStoragesRoute
  AppHiddenLayoutViewProductRoute: typeof AppHiddenLayoutViewProductRoute
}

const AppHiddenLayoutRouteChildren: AppHiddenLayoutRouteChildren = {
  AppHiddenLayoutAddProductRoute: AppHiddenLayoutAddProductRoute,
  AppHiddenLayoutAppSettingsRoute: AppHiddenLayoutAppSettingsRoute,
  AppHiddenLayoutInventoryRoute: AppHiddenLayoutInventoryRoute,
  AppHiddenLayoutStoragesRoute: AppHiddenLayoutStoragesRoute,
  AppHiddenLayoutViewProductRoute: AppHiddenLayoutViewProductRoute,
}

const AppHiddenLayoutRouteWithChildren = AppHiddenLayoutRoute._addFileChildren(
  AppHiddenLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AppHiddenLayoutRoute: AppHiddenLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
