/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppViewProductRouteImport } from './routes/app/view-product'
import { Route as AppInventoryRouteImport } from './routes/app/inventory'
import { Route as AppAddProductRouteImport } from './routes/app/add-product'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppViewProductRoute = AppViewProductRouteImport.update({
  id: '/app/view-product',
  path: '/app/view-product',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/app/inventory',
  path: '/app/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAddProductRoute = AppAddProductRouteImport.update({
  id: '/app/add-product',
  path: '/app/add-product',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/add-product': typeof AppAddProductRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/view-product': typeof AppViewProductRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/add-product': typeof AppAddProductRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/view-product': typeof AppViewProductRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/add-product': typeof AppAddProductRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/view-product': typeof AppViewProductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app/add-product'
    | '/app/inventory'
    | '/app/view-product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/add-product'
    | '/app/inventory'
    | '/app/view-product'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/app/add-product'
    | '/app/inventory'
    | '/app/view-product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AppAddProductRoute: typeof AppAddProductRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppViewProductRoute: typeof AppViewProductRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/view-product': {
      id: '/app/view-product'
      path: '/app/view-product'
      fullPath: '/app/view-product'
      preLoaderRoute: typeof AppViewProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/app/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/add-product': {
      id: '/app/add-product'
      path: '/app/add-product'
      fullPath: '/app/add-product'
      preLoaderRoute: typeof AppAddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AppAddProductRoute: AppAddProductRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppViewProductRoute: AppViewProductRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
